/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package algoritmic;

import java.util.Arrays;
import java.util.List;
import java.util.Random;
import java.util.stream.IntStream;
import javax.swing.JOptionPane;

/**
 *
 * @author Martin
 */
public class GUIvolba extends javax.swing.JFrame {

    private List<String> volby = List.of("Binární hledání", "Lineární hledání");
    private final int POCET_PRVKU = 10;
    private final int MAX_PRVEK = 100;
    private boolean chyba;

    /**
     * Creates new form GUIvolba
     */
    public GUIvolba() {
        initComponents();
        volby.stream().forEach(x -> jComboBox1.addItem(x));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldPosloupnost = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldPrvek = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("zobraz");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("     Zadejte posloupnost čísel oddělených čárkou nebo nechte prázdné pro vygenerování náhodné posloupnosti     ");

        jLabel2.setText("hledaný prvek (nechte prázdné pro náhodný):");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldPosloupnost)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldPrvek)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldPosloupnost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldPrvek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int prvek;
        String input = jTextFieldPrvek.getText();
        if (input.isBlank()) {
            Random random = new Random();
            prvek = random.nextInt(this.MAX_PRVEK);
        } else {
            try {
                prvek = Integer.parseInt(input);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Nesprávný formát hledaného prvku. Zadejte číslo.", "Chyba", JOptionPane.ERROR_MESSAGE);
                //this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
                return;
            }
        }

        chyba = false;
        int[] posloupnost;
        input = jTextFieldPosloupnost.getText();
        if (input.isBlank()) {
            Random random = new Random();
            posloupnost = IntStream.range(0, this.POCET_PRVKU).map(x -> random.nextInt(this.MAX_PRVEK)).toArray();
        } else {
            posloupnost = Arrays.stream(input.split(",")).map(String::trim).mapToInt(x -> {
                try {
                    return Integer.parseInt(x);
                } catch (NumberFormatException e) {
                    //JOptionPane.showMessageDialog(this, "Nesprávný formát posloupnosti. Zadejte čísla ve formátu \"1,2,3,4,5\".", "Chyba", JOptionPane.ERROR_MESSAGE);
                    //this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
                    chyba = true;
                    return 0;
                }
            }).toArray();
        }

        if (chyba) {
            JOptionPane.showMessageDialog(this, "Nesprávný formát posloupnosti. Zadejte čísla ve formátu \"1,2,3,4,5\".", "Chyba", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Algoritmus alg = null;
        String a = jComboBox1.getSelectedItem().toString();
        switch (volby.indexOf(a)) {
            case 0 ->
                alg = new AlBinarniHledani(posloupnost, prvek);
            case 1 ->
                alg = new AlLinearniHledani(posloupnost, prvek);
            default ->
                throw new IllegalArgumentException("Špatná hodnota přečtena v: GUIvolba.jComboBox1");
        }

        new GUIzobrazovani(alg).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIvolba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIvolba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIvolba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIvolba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIvolba().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextFieldPosloupnost;
    private javax.swing.JTextField jTextFieldPrvek;
    // End of variables declaration//GEN-END:variables
}
