/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package algoritmic;

/**
 *
 * @author Martin
 */
public class GUIzobrazovani extends javax.swing.JFrame {

    private Algoritmus algoritmus;

    /**
     * Creates new form GUIzobrazovani
     * @param algoritmus
     */
    public GUIzobrazovani(Algoritmus algoritmus) {
        initComponents();
        this.algoritmus = algoritmus;
        jLabelNadpis.setText(this.algoritmus.getNazev());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonKrokVpred = new javax.swing.JButton();
        jButtonKrokVzad = new javax.swing.JButton();
        jButtonNaZacatek = new javax.swing.JButton();
        jButtonNaKonec = new javax.swing.JButton();
        jLabelNadpis = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonKrokVpred.setText("krok vpřed");
        jPanel1.add(jButtonKrokVpred);

        jButtonKrokVzad.setText("krok vzad");
        jPanel1.add(jButtonKrokVzad);

        jButtonNaZacatek.setText("na začátek");
        jPanel1.add(jButtonNaZacatek);

        jButtonNaKonec.setText("na konec");
        jPanel1.add(jButtonNaKonec);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jLabelNadpis.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNadpis.setText("Pokus");
        getContentPane().add(jLabelNadpis, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIzobrazovani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIzobrazovani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIzobrazovani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIzobrazovani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIzobrazovani(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonKrokVpred;
    private javax.swing.JButton jButtonKrokVzad;
    private javax.swing.JButton jButtonNaKonec;
    private javax.swing.JButton jButtonNaZacatek;
    private javax.swing.JLabel jLabelNadpis;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
