/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package algoritmic;

import java.lang.reflect.InvocationTargetException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Martin
 */
public class GUIzobrazovani extends javax.swing.JFrame {

    private Algoritmus algoritmus;

    /**
     * Creates new form GUIzobrazovani
     *
     * @param algoritmus potomek třídy Algoritmus
     */
    public GUIzobrazovani(Algoritmus algoritmus) {
        initComponents();
        this.algoritmus = algoritmus;
        nadpisLabel.setText(this.algoritmus.getNazev());
        aktualizujGUI();
    }

    private void aktualizujGUI() {
        //něco
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ovladaniPanel = new javax.swing.JPanel();
        krokVpredButton = new javax.swing.JButton();
        krokVzadButton = new javax.swing.JButton();
        naZacatekButton = new javax.swing.JButton();
        naKonecButton = new javax.swing.JButton();
        nadpisLabel = new javax.swing.JLabel();
        pseudokodPanel = new javax.swing.JPanel();
        hlavniPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        krokVpredButton.setText("krok vpřed");
        krokVpredButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                krokVpredButtonActionPerformed(evt);
            }
        });
        ovladaniPanel.add(krokVpredButton);

        krokVzadButton.setText("krok vzad");
        krokVzadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                krokVzadButtonActionPerformed(evt);
            }
        });
        ovladaniPanel.add(krokVzadButton);

        naZacatekButton.setText("na začátek");
        naZacatekButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                naZacatekButtonActionPerformed(evt);
            }
        });
        ovladaniPanel.add(naZacatekButton);

        naKonecButton.setText("na konec");
        naKonecButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                naKonecButtonActionPerformed(evt);
            }
        });
        ovladaniPanel.add(naKonecButton);

        getContentPane().add(ovladaniPanel, java.awt.BorderLayout.PAGE_END);

        nadpisLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nadpisLabel.setText("Pokus");
        getContentPane().add(nadpisLabel, java.awt.BorderLayout.PAGE_START);
        getContentPane().add(pseudokodPanel, java.awt.BorderLayout.LINE_START);
        getContentPane().add(hlavniPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void krokVpredButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_krokVpredButtonActionPerformed
        algoritmus.krokVpred();
        aktualizujGUI();
    }//GEN-LAST:event_krokVpredButtonActionPerformed

    private void krokVzadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_krokVzadButtonActionPerformed
        int novyKrok = algoritmus.krok - 1;
        naZacatekButtonActionPerformed(null);
        while (algoritmus.krok < novyKrok) {
            krokVpredButtonActionPerformed(null);
        }
        aktualizujGUI();
    }//GEN-LAST:event_krokVzadButtonActionPerformed

    private void naZacatekButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_naZacatekButtonActionPerformed
        try {
            algoritmus = (Algoritmus) algoritmus.getClass().getConstructors()[0].newInstance(algoritmus.getPuvodniPosloupnost(), (Integer) algoritmus.getPrvek());
            aktualizujGUI();
        } catch (InstantiationException | IllegalAccessException | IllegalArgumentException | InvocationTargetException ex) {
            Logger.getLogger(GUIzobrazovani.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_naZacatekButtonActionPerformed

    private void naKonecButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_naKonecButtonActionPerformed
        algoritmus.naKonec();
        aktualizujGUI();
    }//GEN-LAST:event_naKonecButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIzobrazovani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIzobrazovani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIzobrazovani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIzobrazovani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIzobrazovani(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel hlavniPanel;
    private javax.swing.JButton krokVpredButton;
    private javax.swing.JButton krokVzadButton;
    private javax.swing.JButton naKonecButton;
    private javax.swing.JButton naZacatekButton;
    private javax.swing.JLabel nadpisLabel;
    private javax.swing.JPanel ovladaniPanel;
    private javax.swing.JPanel pseudokodPanel;
    // End of variables declaration//GEN-END:variables
}
