/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package algoritmic;

import java.lang.reflect.InvocationTargetException;
import java.util.List;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.stream.Collectors;
import javax.swing.JFrame;

/**
 *
 * @author Martin
 */
public class GUIzobrazovani extends javax.swing.JFrame {

    private Algoritmus algoritmus;

    /**
     * Creates new form GUIzobrazovani
     *
     * @param algoritmus potomek třídy Algoritmus
     */
    public GUIzobrazovani(Algoritmus algoritmus) {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.algoritmus = algoritmus;
        nadpisLabel.setText(this.algoritmus.getNazev());
        naZacatekButton.setText("<html>&#9668;&#9668;</html>");
        krokVzadButton.setText("<html>&#9668;</html>");
        krokVpredButton.setText("<html>&#9658;</html>");
        naKonecButton.setText("<html>&#9658;&#9658;</html>");
        aktualizujGUI();
    }

    private void aktualizujGUI() {
        pseudokodLabel.setText("<html>" + this.algoritmus.getPseudokod() + "</html>");
        krokyLabel.setText("<html>" + algoritmus.getKomentareKroku() + "</html>");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ovladaniPanel = new javax.swing.JPanel();
        naZacatekButton = new javax.swing.JButton();
        krokVzadButton = new javax.swing.JButton();
        krokVpredButton = new javax.swing.JButton();
        naKonecButton = new javax.swing.JButton();
        nadpisLabel = new javax.swing.JLabel();
        pseudokodPanel = new javax.swing.JPanel();
        pseudokodLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        hlavniPanel = new javax.swing.JPanel();
        krokyLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        naZacatekButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        naZacatekButton.setText("<<");
        naZacatekButton.setMaximumSize(new java.awt.Dimension(150, 50));
        naZacatekButton.setMinimumSize(new java.awt.Dimension(150, 50));
        naZacatekButton.setPreferredSize(new java.awt.Dimension(150, 50));
        naZacatekButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                naZacatekButtonActionPerformed(evt);
            }
        });
        ovladaniPanel.add(naZacatekButton);

        krokVzadButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        krokVzadButton.setText("<");
        krokVzadButton.setMaximumSize(new java.awt.Dimension(150, 50));
        krokVzadButton.setMinimumSize(new java.awt.Dimension(150, 50));
        krokVzadButton.setPreferredSize(new java.awt.Dimension(150, 50));
        krokVzadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                krokVzadButtonActionPerformed(evt);
            }
        });
        ovladaniPanel.add(krokVzadButton);

        krokVpredButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        krokVpredButton.setText(">");
        krokVpredButton.setMaximumSize(new java.awt.Dimension(150, 50));
        krokVpredButton.setMinimumSize(new java.awt.Dimension(150, 50));
        krokVpredButton.setPreferredSize(new java.awt.Dimension(150, 50));
        krokVpredButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                krokVpredButtonActionPerformed(evt);
            }
        });
        ovladaniPanel.add(krokVpredButton);

        naKonecButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        naKonecButton.setText(">>");
        naKonecButton.setMaximumSize(new java.awt.Dimension(150, 50));
        naKonecButton.setMinimumSize(new java.awt.Dimension(150, 50));
        naKonecButton.setPreferredSize(new java.awt.Dimension(150, 50));
        naKonecButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                naKonecButtonActionPerformed(evt);
            }
        });
        ovladaniPanel.add(naKonecButton);

        getContentPane().add(ovladaniPanel, java.awt.BorderLayout.PAGE_END);

        nadpisLabel.setFont(new java.awt.Font("Tahoma", 0, 72)); // NOI18N
        nadpisLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nadpisLabel.setText("Pokus");
        getContentPane().add(nadpisLabel, java.awt.BorderLayout.PAGE_START);

        pseudokodLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        pseudokodLabel.setText("Pseudokód:");
        pseudokodPanel.add(pseudokodLabel);

        getContentPane().add(pseudokodPanel, java.awt.BorderLayout.LINE_START);

        jScrollPane1.setBorder(null);
        jScrollPane1.setToolTipText("");
        jScrollPane1.setMinimumSize(new java.awt.Dimension(78, 39));
        jScrollPane1.setOpaque(false);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(78, 39));

        krokyLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        krokyLabel.setText("Kroky:");
        hlavniPanel.add(krokyLabel);

        jScrollPane1.setViewportView(hlavniPanel);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void krokVpredButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_krokVpredButtonActionPerformed
        algoritmus.krokVpred();
        aktualizujGUI();
    }//GEN-LAST:event_krokVpredButtonActionPerformed

    private void krokVzadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_krokVzadButtonActionPerformed
        int novyKrok = algoritmus.getKrok() - 1;
        naZacatekButtonActionPerformed(null);
        while (algoritmus.getKrok() < novyKrok) {
            krokVpredButtonActionPerformed(null);
        }
        //aktualizujGUI();
    }//GEN-LAST:event_krokVzadButtonActionPerformed

    private void naZacatekButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_naZacatekButtonActionPerformed
        try {
            algoritmus = (Algoritmus) algoritmus.getClass().getConstructors()[0].newInstance(algoritmus.getPosloupnost(), (Integer) algoritmus.getPrvek());
            aktualizujGUI();
        } catch (InstantiationException | IllegalAccessException | IllegalArgumentException | InvocationTargetException ex) {
            Logger.getLogger(GUIzobrazovani.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_naZacatekButtonActionPerformed

    private void naKonecButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_naKonecButtonActionPerformed
        algoritmus.naKonec();
        aktualizujGUI();
    }//GEN-LAST:event_naKonecButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIzobrazovani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIzobrazovani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIzobrazovani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIzobrazovani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIzobrazovani(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel hlavniPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton krokVpredButton;
    private javax.swing.JButton krokVzadButton;
    private javax.swing.JLabel krokyLabel;
    private javax.swing.JButton naKonecButton;
    private javax.swing.JButton naZacatekButton;
    private javax.swing.JLabel nadpisLabel;
    private javax.swing.JPanel ovladaniPanel;
    private javax.swing.JLabel pseudokodLabel;
    private javax.swing.JPanel pseudokodPanel;
    // End of variables declaration//GEN-END:variables
}
